<?xml version="1.0" encoding="UTF-8"?>
<!--
  Licensed to the Apache Software Foundation (ASF) under one or more
  contributor license agreements. See the NOTICE file distributed with
  this work for additional information regarding copyright ownership.
  The ASF licenses this file to You under the Apache License, Version 2.0
  (the "License"); you may not use this file except in compliance with
  the License. You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.apache.ozone</groupId>
    <artifactId>ozone-main</artifactId>
    <version>2.2.1</version>
  </parent>

  <artifactId>ozone-custom-module</artifactId>
  <packaging>jar</packaging>
  <name>Apache Ozone Custom Module</name>
  <description>Apache Ozone Custom Features Project</description>

  <properties>
    <!-- aggregates the Ozone classpath for custom development, most modules are not referenced directly -->
    <mdep.analyze.skip>true</mdep.analyze.skip>
  </properties>
  <dependencies>
    <dependency>
      <groupId>org.apache.ozone</groupId>
      <artifactId>hdds-client</artifactId>
      <version>${hdds.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.ozone</groupId>
      <artifactId>hdds-common</artifactId>
      <version>${hdds.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.ozone</groupId>
      <artifactId>hdds-config</artifactId>
      <version>${hdds.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.ozone</groupId>
      <artifactId>hdds-container-service</artifactId>
      <version>${hdds.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.ozone</groupId>
      <artifactId>hdds-docs</artifactId>
      <version>${hdds.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.ozone</groupId>
      <artifactId>hdds-erasurecode</artifactId>
      <version>${hdds.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.ozone</groupId>
      <artifactId>hdds-interface-client</artifactId>
      <version>${hdds.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.ozone</groupId>
      <artifactId>hdds-rocks-native</artifactId>
      <version>${hdds.rocks.native.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.ozone</groupId>
      <artifactId>hdds-server-framework</artifactId>
      <version>${hdds.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.ozone</groupId>
      <artifactId>hdds-server-scm</artifactId>
      <version>${hdds.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.ozone</groupId>
      <artifactId>ozone-client</artifactId>
      <version>${ozone.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.ozone</groupId>
      <artifactId>ozone-common</artifactId>
      <version>${ozone.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.ozone</groupId>
      <artifactId>ozone-csi</artifactId>
      <version>${ozone.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.ozone</groupId>
      <artifactId>ozone-datanode</artifactId>
      <version>${ozone.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.ozone</groupId>
      <artifactId>ozone-filesystem</artifactId>
      <version>${ozone.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.ozone</groupId>
      <artifactId>ozone-filesystem-common</artifactId>
      <version>${ozone.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.ozone</groupId>
      <artifactId>ozone-filesystem-hadoop2</artifactId>
      <version>${ozone.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.ozone</groupId>
      <artifactId>ozone-filesystem-hadoop3</artifactId>
      <version>${ozone.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.ozone</groupId>
      <artifactId>ozone-filesystem-shaded</artifactId>
      <version>${ozone.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.ozone</groupId>
      <artifactId>ozone-httpfsgateway</artifactId>
      <version>${ozone.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.ozone</groupId>
      <artifactId>ozone-insight</artifactId>
      <version>${hdds.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.ozone</groupId>
      <artifactId>ozone-interface-client</artifactId>
      <version>${ozone.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.ozone</groupId>
      <artifactId>ozone-interface-storage</artifactId>
      <version>${ozone.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.ozone</groupId>
      <artifactId>ozone-manager</artifactId>
      <version>${ozone.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.ozone</groupId>
      <artifactId>ozone-recon</artifactId>
      <version>${ozone.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.ozone</groupId>
      <artifactId>ozone-s3-secret-store</artifactId>
      <version>${hdds.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.ozone</groupId>
      <artifactId>ozone-s3gateway</artifactId>
      <version>${ozone.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.ozone</groupId>
      <artifactId>ozone-tools</artifactId>
      <version>${ozone.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.ozone</groupId>
      <artifactId>rocksdb-checkpoint-differ</artifactId>
      <version>${hdds.version}</version>
    </dependency>
  </dependencies>

  <build>
    <resources>
      <resource>
        <filtering>false</filtering>
        <directory>${basedir}/src/main/resources</directory>
        <excludes>
          <exclude>custom-module-version-info.properties</exclude>
        </excludes>
      </resource>
      <resource>
        <filtering>true</filtering>
        <directory>${basedir}/src/main/resources</directory>
        <includes>
          <include>custom-module-version-info.properties</include>
        </includes>
      </resource>
    </resources>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>${maven-surefire-plugin.version}</version>
        <configuration>
          <skipTests>true</skipTests>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.hadoop</groupId>
        <artifactId>hadoop-maven-plugins</artifactId>
        <executions>
          <execution>
            <id>version-info</id>
            <goals>
              <goal>version-info</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <source>
                <directory>${basedir}</directory>
                <includes>
                  <include>*/src/main/java/**/*.java</include>
                </includes>
              </source>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>com.github.spotbugs</groupId>
        <artifactId>spotbugs-maven-plugin</artifactId>
        <configuration>
          <excludeFilterFile>${basedir}/dev-support/findbugsExcludeFile.xml</excludeFilterFile>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-checkstyle-plugin</artifactId>
        <version>${maven-checkstyle-plugin.version}</version>
        <configuration>
          <configLocation>../hadoop-hdds/dev-support/checkstyle/checkstyle.xml</configLocation>
          <suppressionsLocation>../hadoop-hdds/dev-support/checkstyle/suppressions.xml</suppressionsLocation>
          <includeTestSourceDirectory>true</includeTestSourceDirectory>
          <failOnViolation>false</failOnViolation>
          <format>xml</format>
          <format>html</format>
          <outputFile>${project.build.directory}/test/checkstyle-errors.xml</outputFile>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>com.puppycrawl.tools</groupId>
            <artifactId>checkstyle</artifactId>
            <version>${checkstyle.version}</version>
          </dependency>
        </dependencies>
      </plugin>
    </plugins>
  </build>

</project>
