@startuml
'https://plantuml.com/sequence-diagram

'autonumber

Ambari -> Ozone: генерирует пароль на раскатке кластера в jceks
User --> Ozone: ozone s3 getsecret - создание секрета

Ozone -> Ozone: Читает пароль из jceks
Ozone -> Ozone: генерирует секрета на основе пароля

Ozone -> SecMan: Сохраняет секрет

Ozone --> User: secret="..."
@enduml